# vim:sw=2:et:

sudo: false

language: erlang

otp_release:
  - 22.0
  - 21.3
  - 19.3

before_script:
  - kerl list installations

script:
  - rebar3 xref
  - rebar3 eunit
  - rebar3 ct --readable=false
  - rebar3 dialyzer
